psyfood/pyqmix-web

.gitignore
pyqmix_backend/app.py
pyqmix_backend/test_connection_pumps.py
pyqmix_frontend/src/App.css
pyqmix_frontend/src/App.js
pyqmix_frontend/src/temp.js

Essentially bring `pyqmix-web` to a usable state ;)

Huge refactor, new features

---

pyqmix_backend/app.py
pyqmix_backend/test_pump_connection_laptop.py
pyqmix_frontend/src/App.css
pyqmix_frontend/src/App.js
pyqmix_frontend/src/temp.js

Solves issue #8 
Solution assumes that all configurations are stored in this directory: C:\Users\Public\Documents\QmixElements\Projects\default_project\Configurations

FE: dropdown list of available Qmix configurations. 

---

pyqmix_backend/app.py
pyqmix_frontend/src/App.js

This PR includes the following changes:
- Enable user to select syringe type. Closes #6.
- Remove modal from `targetVolume` option
- Disable test session per default

ENH, RF: Allow user to set syringe size & small changes

---

EXECUTABLE.md

Please also check the entire document. The first commit was pushed directly to master.

DOC: Rewording of documentation.

---

EXECUTABLE.md
README.md

BF: Minor typos in documentation

---

CHANGES.md
pyqmix_backend/app.py
pyqmix_frontend/src/App.css
pyqmix_frontend/src/App.js

Display pyqmix version

---

CHANGES.md

DOC/PKG: Update changelog in preparation for release

---

CHANGES.md
pyqmix_frontend/src/App.js

NF: Display pyqmix version on frontend

---

CHANGES.md
pyqmix_frontend/package-lock.json
pyqmix_frontend/package.json

Fixes several security issues.

PKG: Update to react-scripts 2.1.3

---

CHANGES.md
EXECUTABLE.md
pyqmix_backend/run.py
pyqmix_backend/run.spec
pyqmix_frontend/src/App.css
pyqmix_frontend/src/App.js

Fix and update instructions to create an executable. 
Also, minor bug fixes to style modals in the frontend-build.

FE: Executable instructions

---

CHANGES.md
EXECUTABLE.md
pyqmix_backend/run.py
setup.cfg

The pull request resolves #43, while ensuring that the standalone still compiles correctly.

Fix to enable entry point

---

CHANGES.md
pyqmix_frontend/package-lock.json
pyqmix_frontend/package.json

Picked up #48 again, and seems to be working fine.

PKG: Update multiple dependencies (also fixes potential security issues)

---

CHANGES.md
pyqmix_frontend/package-lock.json
pyqmix_frontend/package.json

PKG: Update reactstrap

---

CHANGES.md
pyqmix_frontend/package.json
pyqmix_frontend/src/App.js

PKG, BF: Update react, react-dom; fix small bug in App.js

---

CHANGES.md
DEVELOPER_NOTES.md
EXECUTABLE.md
pyqmix_frontend/package.json

RF, DOC: Frontend uses search paths relative to index.html, add some notes for developers

---

CHANGES.md
pyqmix_frontend/src/App.css

ENH: Fix title on top (while scrolling), and add a little shadow

---

CHANGES.md

DOC: Fix typo

---

CHANGES.md
pyqmix_frontend/src/App.css
pyqmix_frontend/src/App.js

RF, ENH: Refactor all input fields into their own component; disable input until pump was selected; Disconnect button is now red; cleanups

---

CHANGES.md
DEVELOPER_NOTES.md
pyqmix_backend/backend_app.py

NF: Allow users to enable backend test mode via environment variable

---

pyqmix_backend/backend_app.py

BF: PYQMIX_TEST_MODE set to `1` was not treated correctly
